### ISSUE TITLE
Parachute + Popeye + Vermin: issue

### ISSUE THREAD

**Issue by megane72GH** [agg23/fpga-gameandwatch#16]
If activated the Acc. LCD Timing - Accurate LCD timing the LCD segments will light up and work evenly. Without works flowlessy.

https://github.com/agg23/fpga-gameandwatch/assets/104077610/9e8e7c8b-65f8-44a7-9084-a3a2cee81772

Same in Popeye and Vermin.

**Comment by agg23** [comment]
Accurate LCD Timing generally does not bring a good experience. Since modern LCDs don’t have persistence like the GnW ones, clocking the LCD update logic at the correct speed results in a ton of flicker, like you’ve shown.

The feature exists just for curiosity and “accuracy”, but it will never produce good results.
